name: Secure CI/CD Pipeline (GUI Setup)

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: "kubernetestest-494210"
  REGION: "us-central1"
  SERVICE_NAME: "demo-app"
  
  # Paste values from Step 2 & Step 5
  WORKLOAD_IDENTITY_PROVIDER: "projects/204216084864/locations/global/workloadIdentityPools/github-actions-pool-010/providers/github-provider"
  SERVICE_ACCOUNT: "github-actions-deployer@kubernetestest-494210.iam.gserviceaccount.com"
  ARTIFACT_REGISTRY: "us-central1-docker.pkg.dev/kubernetestest-494210/devops-lab-repo"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker for GCP Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG="${{ env.ARTIFACT_REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.IMAGE_TAG }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated
